language: go

go: 1.3.3

install:
  - echo 'yes' | sudo add-apt-repository ppa:fkrull/deadsnakes
  - sudo apt-get update -qq
  - sudo apt-get install -qq libonig-dev mercurial python3.4 python3.4-dev xclip

script:
  - ./tasks/ci/lime.sh
  - ./tasks/ci/gofmt.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3e692a5224c8490f19bd
    on_success: change
    on_failure: always
    on_start: false
