language: go

go: 1.1

before_install:
  - git submodule update --init --recursive

install:
  - go get -d code.google.com/p/log4go
  - go get -d github.com/quarnster/parser
  - go get -d github.com/quarnster/completion
  - go get -d github.com/quarnster/util
  - go get -d github.com/howeyc/fsnotify
  - sudo apt-get update -qq
  - sudo apt-get install -qq libonig-dev

script:
  - ./scripts/ci/gopy.sh
  - ./scripts/ci/completion.sh
  - ./scripts/ci/lime.sh
